version: '3.9'
services:
  card_db:
    image: postgres:latest
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: myuser
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d myuser -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  pgdata:
    driver: local
